name: CI

on:
  push:
    paths:
      - 'index.html'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'index.html'
      - '.github/workflows/ci.yml'
  workflow_dispatch: {}

jobs:
  validate:
    uses: shani8dev/shani-ci-commons/.github/workflows/validate-html.yml@main
    with:
      strict-parse: false
      require-sri: true

  security:
    name: Security
    uses: shani8dev/shani-ci-commons/.github/workflows/security.yml@main
    with:
      scan-type: secrets
    needs: validate